name: Test Simulate Variants

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'simulate**.smk'
      - 'workflow/envs/harpy.yaml'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - 'test/vcf/test.bcf'
      - 'workflow/scripts/simuG.pl'
      - '**__main__.py'

  pull_request:
    branches:
      - 'dev'
    paths:
      - 'simulate**.smk'
      - 'workflow/envs/harpy.yaml'
      - '**helperfunctions.py'
      - '**printfunctions.py'
      - '**fileparsers.py'
      - 'test/vcf/test.bcf'
      - 'workflow/scripts/simuG.pl'
      - '**__main__.py'

env:
  CACHE_NUMBER: 0  # increase to reset cache manually

jobs:
  build:
    name: test simulations
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup mamba
        uses: mamba-org/setup-micromamba@v1
        env:
          ACTIONS_STEP_DEBUG: true
        with:
          init-shell: bash
          generate-run-shell: true
          environment-file: workflow/envs/harpy.yaml
          cache-environment: true
          post-cleanup: 'all'
          log-level: error
      - name: Install harpy
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade build && python3 -m build
          pip install dist/*.whl
          resources/buildforCI.sh

      - name: simulate random snps/indels
        shell: micromamba-shell {0}
        run: |
          harpy simulate snpindel --snp-count 10 --indel-count 10 -z 0.5 test/genome/genome.fasta.gz
          harpy simulate snpindel --prefix Simulate/snpvcf --snp-vcf Simulate/snpindel/sim.snpindel.snp.hap1.vcf --indel-vcf Simulate/snpindel/sim.snpindel.indel.hap1.vcf test/genome/genome.fasta.gz

      - name: simulate inversions
        shell: micromamba-shell {0}
        if: always()
        run: |
          harpy simulate inversion --count 10 -z 0.5 test/genome/genome.fasta.gz
          harpy simulate inversion --prefix Simulate/invvcf --vcf Simulate/inversion/sim.inversion.hap1.vcf test/genome/genome.fasta.gz

      - name: simulate cnv
        shell: micromamba-shell {0}
        if: always()
        run: |
          harpy simulate cnv --count 10 -z 0.5 test/genome/genome.fasta.gz
          harpy simulate cnv --prefix Simulate/cnvvcf --vcf Simulate/inversion/sim.cnv.hap1.vcf test/genome/genome.fasta.gz


      - name: simulate translocations
        shell: micromamba-shell {0}
        if: always()
        run: |
          harpy simulate translocation --count 10 -z 0.5 test/genome/genome.fasta.gz
          harpy simulate translocation --prefix Simulate/transvcf --vcf Simulate/translocation/sim.translocation.hap1.vcf test/genome/genome.fasta.gz

